[install]
# Use npm registry for packages
registry = "https://registry.npmjs.org/"

[install.scopes]
# Configure scoped packages if needed

[run]
# Environment variables for running scripts
env = [
  "NODE_ENV=development"
]

[build]
# Build configuration
target = "node"
outdir = "dist"
minify = false
sourcemap = "external"

[test]
# Test configuration
# preload = ["./src/test-setup.ts"]
